[2024-03-16T01:14:55.009-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_PII_Data_Detection.missing_values_removal scheduled__2024-03-16T05:06:00+00:00 [queued]>
[2024-03-16T01:14:55.015-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_PII_Data_Detection.missing_values_removal scheduled__2024-03-16T05:06:00+00:00 [queued]>
[2024-03-16T01:14:55.015-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-16T01:14:55.037-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): missing_values_removal> on 2024-03-16 05:06:00+00:00
[2024-03-16T01:14:55.042-0400] {standard_task_runner.py:60} INFO - Started process 414122 to run task
[2024-03-16T01:14:55.045-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'test_PII_Data_Detection', 'missing_values_removal', 'scheduled__2024-03-16T05:06:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/src/airflow.py', '--cfg-path', '/tmp/tmplrcngwmo']
[2024-03-16T01:14:55.047-0400] {standard_task_runner.py:88} INFO - Job 342: Subtask missing_values_removal
[2024-03-16T01:14:55.086-0400] {task_command.py:423} INFO - Running <TaskInstance: test_PII_Data_Detection.missing_values_removal scheduled__2024-03-16T05:06:00+00:00 [running]> on host MSI.
[2024-03-16T01:14:55.162-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_PII_Data_Detection' AIRFLOW_CTX_TASK_ID='missing_values_removal' AIRFLOW_CTX_EXECUTION_DATE='2024-03-16T05:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-16T05:06:00+00:00'
[2024-03-16T01:14:55.164-0400] {logging_mixin.py:188} INFO - fetched project directory successfully /home/vineshgvk/PII-Data
[2024-03-16T01:14:55.170-0400] {logging_mixin.py:188} INFO - fetched path from load_gcp_data task /home/vineshgvk/PII-Data/dags/processed/train_com.json
[2024-03-16T01:14:55.171-0400] {logging_mixin.py:188} INFO - Loading data from: /home/vineshgvk/PII-Data/dags/processed/train_com.json
[2024-03-16T01:14:55.178-0400] {logging_mixin.py:188} INFO - created outputPath /home/vineshgvk/PII-Data/dags/processed/missing_values.pkl
[2024-03-16T01:14:55.180-0400] {logging_mixin.py:188} INFO - Data pickled after naHandling at /home/vineshgvk/PII-Data/dags/processed/missing_values.pkl
[2024-03-16T01:14:55.180-0400] {python.py:202} INFO - Done. Returned value was: /home/vineshgvk/PII-Data/dags/processed/missing_values.pkl
[2024-03-16T01:14:55.199-0400] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=test_PII_Data_Detection, task_id=missing_values_removal, execution_date=20240316T050600, start_date=20240316T051455, end_date=20240316T051455
[2024-03-16T01:14:55.204-0400] {logging_mixin.py:188} WARNING - /home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-16T01:14:55.211-0400] {logging_mixin.py:188} WARNING - /home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-03-16T01:14:55.212-0400] {email.py:270} INFO - Email alerting: attempt 1
[2024-03-16T01:16:00.777-0400] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-03-16T01:16:00.780-0400] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 414122. PIDs of all processes in the group: [414122]
[2024-03-16T01:16:00.780-0400] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 414122
[2024-03-16T01:16:00.780-0400] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-16T01:16:00.780-0400] {taskinstance.py:1127} ERROR - Error when executing task_success_alert callback
Traceback (most recent call last):
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1124, in _run_finished_callback
    callback(context)
  File "/home/vineshgvk/PII-Data/dags/src/airflow.py", line 201, in task_success_alert
    send_email(to='gvk7663@gmail.com', subject=subject, html_content=html_content)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-16T01:16:00.833-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=414122, status='terminated', exitcode=0, started='01:14:54') (414122) terminated with exit code 0
