[2024-03-16T00:32:16.387-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PII_Data_Detection.load_data_from_gcp scheduled__2024-03-15T03:18:00+00:00 [queued]>
[2024-03-16T00:32:16.394-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PII_Data_Detection.load_data_from_gcp scheduled__2024-03-15T03:18:00+00:00 [queued]>
[2024-03-16T00:32:16.394-0400] {taskinstance.py:2193} INFO - Starting attempt 6 of 7
[2024-03-16T00:32:16.416-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_from_gcp> on 2024-03-15 03:18:00+00:00
[2024-03-16T00:32:16.421-0400] {standard_task_runner.py:60} INFO - Started process 380735 to run task
[2024-03-16T00:32:16.424-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'PII_Data_Detection', 'load_data_from_gcp', 'scheduled__2024-03-15T03:18:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/src/airflow.py', '--cfg-path', '/tmp/tmpi2lfx5rk']
[2024-03-16T00:32:16.425-0400] {standard_task_runner.py:88} INFO - Job 318: Subtask load_data_from_gcp
[2024-03-16T00:32:16.457-0400] {task_command.py:423} INFO - Running <TaskInstance: PII_Data_Detection.load_data_from_gcp scheduled__2024-03-15T03:18:00+00:00 [running]> on host MSI.
[2024-03-16T00:32:16.589-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='PII_Data_Detection' AIRFLOW_CTX_TASK_ID='load_data_from_gcp' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T03:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T03:18:00+00:00'
[2024-03-16T00:32:16.591-0400] {logging_mixin.py:188} INFO - environment path is set
[2024-03-16T00:32:16.591-0400] {logging_mixin.py:188} INFO - current project directory /home/vineshgvk/PII-Data
[2024-03-16T00:32:16.591-0400] {logging_mixin.py:188} INFO - destination directory at /home/vineshgvk/PII-Data/dags/processed
[2024-03-16T00:32:16.591-0400] {logging_mixin.py:188} INFO - Trying to create a storage client connection
[2024-03-16T00:32:16.676-0400] {logging_mixin.py:188} INFO - Trying to fetch the specified bucket name
[2024-03-16T00:32:17.094-0400] {logging_mixin.py:188} INFO - Specified bucket is successfully fetched
[2024-03-16T00:32:17.094-0400] {logging_mixin.py:188} INFO - Starting iteration on files from bucket
[2024-03-16T00:32:17.095-0400] {logging_mixin.py:188} INFO - defined the blob to fetch <Blob: pii_data_load, Data/train_com.json, None>
[2024-03-16T00:32:17.095-0400] {logging_mixin.py:188} INFO - local file path is created at /home/vineshgvk/PII-Data/dags/processed/train_com.json
[2024-03-16T00:32:17.095-0400] {logging_mixin.py:188} WARNING - --- Logging error ---
[2024-03-16T00:32:17.096-0400] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-03-16T00:32:17.097-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2024-03-16T00:32:17.097-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2024-03-16T00:32:17.097-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2024-03-16T00:32:17.097-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2024-03-16T00:32:17.098-0400] {logging_mixin.py:188} WARNING - TypeError: not all arguments converted during string formatting
[2024-03-16T00:32:17.098-0400] {logging_mixin.py:188} WARNING - Call stack:
[2024-03-16T00:32:17.100-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-16T00:32:17.100-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 216, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 278, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/jobs/job.py", line 393, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/jobs/job.py", line 422, in execute_job
    ret = execute_callable()
[2024-03-16T00:32:17.101-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 165, in _execute
    self.task_runner.start()
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 48, in start
    self.process = self._start_by_fork()
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 100, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 438, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 218, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 297, in _run_raw_task
    return ti._run_raw_task(
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2532, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-03-16T00:32:17.102-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2549, in _execute_task
    return _execute_task(self, context, task_orig)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/PII-Data/dags/src/data_download.py", line 63, in load_data_from_gcp_and_save_as_json
    logging.info('works', local_file_path)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2024-03-16T00:32:17.103-0400] {logging_mixin.py:188} WARNING -   File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 272, in emit
    self.handler.emit(record)
[2024-03-16T00:32:17.104-0400] {logging_mixin.py:188} WARNING - Message: 'works'
Arguments: ('/home/vineshgvk/PII-Data/dags/processed/train_com.json',)
[2024-03-16T00:32:17.304-0400] {logging_mixin.py:188} INFO - File train_com.json downloaded and saved as /home/vineshgvk/PII-Data/dags/processed/train_com.json.
[2024-03-16T00:32:17.305-0400] {python.py:202} INFO - Done. Returned value was: /home/vineshgvk/PII-Data/dags/processed/train_com.json
[2024-03-16T00:32:17.326-0400] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=PII_Data_Detection, task_id=load_data_from_gcp, execution_date=20240315T031800, start_date=20240316T043216, end_date=20240316T043217
[2024-03-16T00:32:17.333-0400] {logging_mixin.py:188} WARNING - /home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-16T00:32:17.340-0400] {logging_mixin.py:188} WARNING - /home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-03-16T00:32:17.340-0400] {email.py:270} INFO - Email alerting: attempt 1
[2024-03-16T00:32:23.383-0400] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 380735. PIDs of all processes in the group: [380735]
[2024-03-16T00:32:23.384-0400] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 380735
[2024-03-16T00:32:23.384-0400] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-16T00:32:23.385-0400] {taskinstance.py:1127} ERROR - Error when executing task_success_alert callback
Traceback (most recent call last):
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1124, in _run_finished_callback
    callback(context)
  File "/home/vineshgvk/PII-Data/dags/src/airflow.py", line 200, in task_success_alert
    send_email(to='gvk7663@gmail.com', subject=subject, html_content=html_content)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
  File "/home/vineshgvk/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
